### ISSUE TITLE
Crashes with certain uses of the wayland branch of rofi

### ISSUE THREAD

**Issue by BenJarg** [djpohly/dwl#244]
When trying multiple times to launch an app that won't correctly launch from rofi (the wayland fork), dwl will sometimes crash with a segfault. This only seems to happen when the cursor is over the rofi window prior to making the selection. It doesn't seem to be able to be consistently reproducible, and sometimes needs to be tried more times than others before a crash occurs. The apps I'm launching that crash immediately are, for example, gtk emacs and Zotero with the `GDK_BACKEND` variable set to `wayland` (setting it to `x11` instead will get these to correctly launch inXWayland and not crash dwl, but them crashing shouldn't crash dwl of course). I can reproduce this while using the current main branch. 

The gdb bracktrace varies from crash to crash, but the 3 different ones I see are listed below:
```
#0  client_surface (c=0x555555e93aa0) at client.h:26
#1  0x000055555555e35a in focusclient (c=0x555555e93aa0, lift=0) at dwl.c:1113
#2  0x000055555555f7cf in pointerfocus (c=0x555555e93aa0, surface=0x555555f221f0, sx=291.53515625, sy=245.92578125, time=18918957) at dwl.c:1604
#3  0x000055555555f30a in motionnotify (time=18918957) at dwl.c:1488
#4  0x000055555555f03b in motionabsolute (listener=0x5555555676c0 <cursor_motion_absolute>, data=0x7fffffffdd40) at dwl.c:1443
#5  0x00007ffff7f661ec in wlr_signal_emit_safe () from /usr/lib/libwlroots.so.10
#6  0x00007ffff7f661ec in wlr_signal_emit_safe () from /usr/lib/libwlroots.so.10
#7  0x00007ffff7f25041 in ?? () from /usr/lib/libwlroots.so.10
#8  0x00007ffff76c2e6d in ?? () from /usr/lib/libffi.so.7
#9  0x00007ffff76c22aa in ?? () from /usr/lib/libffi.so.7
#10 0x00007ffff78f79ae in ?? () from /usr/lib/libwayland-client.so.0
#11 0x00007ffff78f80f3 in ?? () from /usr/lib/libwayland-client.so.0
#12 0x00007ffff78f82cc in wl_display_dispatch_queue_pending () from /usr/lib/libwayland-client.so.0
#13 0x00007ffff7f23e54 in ?? () from /usr/lib/libwlroots.so.10
#14 0x00007ffff7ed2c12 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
#15 0x00007ffff7ed3365 in wl_display_run () from /usr/lib/libwayland-server.so.0
#16 0x000055555556021c in run (startup_cmd=0x0) at dwl.c:1799
#17 0x0000555555561ceb in main (argc=1, argv=0x7fffffffe4b8) at dwl.c:2563
```

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7c61536 in __GI_abort () at abort.c:79
#2  0x00007ffff7c6141f in __assert_fail_base (fmt=0x7ffff7dc9ea8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff7f6fd58 "wlr_texture_is_gles2(wlr_texture)", 
    file=0x7ffff7f6f20e "render/gles2/texture.c", line=28, function=<optimized out>) at assert.c:92
#3  0x00007ffff7c70792 in __GI___assert_fail (assertion=0x7ffff7f6fd58 "wlr_texture_is_gles2(wlr_texture)", file=0x7ffff7f6f20e "render/gles2/texture.c", line=28, function=0x7ffff7f73650 "gles2_get_texture")
    at assert.c:101
#4  0x00007ffff7f0a7c5 in ?? () from /usr/lib/libwlroots.so.10
#5  0x00007ffff7f1692f in ?? () from /usr/lib/libwlroots.so.10
#6  0x00007ffff7f38e2d in ?? () from /usr/lib/libwlroots.so.10
#7  0x00007ffff7f38fc8 in ?? () from /usr/lib/libwlroots.so.10
#8  0x00007ffff7f2d98d in ?? () from /usr/lib/libwlroots.so.10
#9  0x00007ffff7f2d9b4 in ?? () from /usr/lib/libwlroots.so.10
#10 0x00007ffff7f2d9b4 in ?? () from /usr/lib/libwlroots.so.10
#11 0x00007ffff7f392bf in wlr_scene_render_output () from /usr/lib/libwlroots.so.10
#12 0x00007ffff7f39743 in wlr_scene_output_commit () from /usr/lib/libwlroots.so.10
#13 0x000055555555fc59 in rendermon (listener=0x555555cc4e20, data=0x555555cc0bb0) at dwl.c:1700
#14 0x00007ffff7f661ec in wlr_signal_emit_safe () from /usr/lib/libwlroots.so.10
#15 0x00007ffff7ed2b2b in wl_event_loop_dispatch_idle () from /usr/lib/libwayland-server.so.0
#16 0x00007ffff7ed2c65 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
#17 0x00007ffff7ed3365 in wl_display_run () from /usr/lib/libwayland-server.so.0
#18 0x00005555555601f2 in run (startup_cmd=0x0) at dwl.c:1800
#19 0x0000555555561cc1 in main (argc=1, argv=0x7fffffffe4b8) at dwl.c:2564
```

```
#2  0x00007ffff55dd111 in ?? () from /usr/lib64/dri/radeonsi_dri.so
#3  0x00007ffff55dd229 in ?? () from /usr/lib64/dri/radeonsi_dri.so
#4  0x00007ffff55e674f in ?? () from /usr/lib64/dri/radeonsi_dri.so
#5  0x00007ffff55b6318 in ?? () from /usr/lib64/dri/radeonsi_dri.so
#6  0x00007ffff55b6371 in ?? () from /usr/lib64/dri/radeonsi_dri.so
#7  0x00007ffff56d5e30 in ?? () from /usr/lib64/dri/radeonsi_dri.so
#8  0x00007ffff7f0bdc9 in ?? () from /usr/lib/libwlroots.so.10
#9  0x00007ffff7f39727 in wlr_scene_output_commit () from /usr/lib/libwlroots.so.10
#10 0x000055555555fc59 in rendermon (listener=0x555555cc0fb0, data=0x555555cc4e50) at dwl.c:1700
#11 0x00007ffff7f661ec in wlr_signal_emit_safe () from /usr/lib/libwlroots.so.10
#12 0x00007ffff7ed2b2b in wl_event_loop_dispatch_idle () from /usr/lib/libwayland-server.so.0
#13 0x00007ffff7ed2c65 in wl_event_loop_dispatch () from /usr/lib/libwayland-server.so.0
#14 0x00007ffff7ed3365 in wl_display_run () from /usr/lib/libwayland-server.so.0
#15 0x00005555555601f2 in run (startup_cmd=0x0) at dwl.c:1800
#16 0x0000555555561cc1 in main (argc=1, argv=0x7fffffffe4b8) at dwl.c:2564
```

This consistently seems to happen soon after `destroylayersurfacenotify` is called on the rofi LayerSurface and it's free'd. From there, in the first backtrace anyway, it seems the corresponding rofi scene node is still found by `xytonode` and used by `focusclient` after deallocation.

**Comment by Sevz17** [comment]
I've pushed https://github.com/djpohly/dwl/commit/48ec914f439c962ac14f75bfcb0c40282c6a0de3, I think it fixes this issue.

**Comment by BenJarg** [comment]
It would seem as it does fix it, thanks!
