### ISSUE TITLE
dwl on x11 backend crash on start with wlroots 0.16.1

### ISSUE THREAD

**Issue by guyuming76** [djpohly/dwl#369]
```
dwl: backend/x11/output.c:682: handle_x11_present_event: Assertion `buffer->n_busy >

Thread 1 "dwl" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) :
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6,
    no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7c863bf in __pthread_kill_internal (signo=6,
    threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7c37ecd in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7c2247b in __GI_abort () at abort.c:79
#4  0x00007ffff7c22397 in __assert_fail_base (
    fmt=0x7ffff7d96880 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x7ffff7f85857 "buffer->n_busy > 0",
    file=0x7ffff7f85604 "backend/x11/output.c", line=682, function=<optimized out>)
    at assert.c:92
#5  0x00007ffff7c30c13 in __GI___assert_fail (
    assertion=0x7ffff7f85857 "buffer->n_busy > 0",
    file=0x7ffff7f85604 "backend/x11/output.c", line=682,
    function=0x7ffff7f85910 <__PRETTY_FUNCTION__.0> "handle_x11_present_event")
    at assert.c:101
#6  0x00007ffff7ef2309 in handle_x11_present_event (x11=0x55555556f220,
    event=0x555555d05c90) at ../backend/x11/output.c:682
#7  0x00007ffff7eedbc6 in handle_x11_event (x11=0x55555556f220,
    event=0x555555d05c90) at ../backend/x11/backend.c:108
#8  0x00007ffff7eedca9 in x11_event (fd=6, mask=1, data=0x55555556f220)
    at ../backend/x11/backend.c:141
#9  0x00007ffff7e76fbc in wl_event_source_fd_dispatch (source=0x55555556f940,
    ep=0x7fffffffd900) at ../wayland-1.21.0/src/event-loop.c:112
#10 0x00007ffff7e786d7 in wl_event_loop_dispatch (loop=0x55555556f0a0, timeout=-1)
    at ../wayland-1.21.0/src/event-loop.c:1027
#11 0x00007ffff7e74b8d in wl_display_run (display=0x55555556efb0)
    at ../wayland-1.21.0/src/wayland-server.c:1431
#12 0x0000555555560c92 in run (startup_cmd=0x0) at dwl.c:2213
#13 0x0000555555564ab0 in main (argc=1, argv=0x7fffffffdc48) at dwl.c:3661
(gdb)

```

**Comment by sevz17** [comment]
Fixed by https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/bc8260f377b5d1b254cbd3b0eacf5e51aeb005e5

**Comment by pm4rcin** [comment]
It was backported to 0.16.2 so we can close. It's in arch repos already.
