### ISSUE TITLE
Segfault of current master on Alpine Linux

### ISSUE THREAD

**Issue by matu3ba** [djpohly/dwl#44]
After installing all necessary packages and building wlroots from master (commit 9feeb2738dfc5a2b07a817938cef9d553d0a26ee) (missing elogind and xbc-error and systemd) and `dwl` (commit 0816b33d333e949437a465b0dcf8461ba4c099a5) I got the following segfault:

**gdb log**

Starting program: /home/user/git/dwl/dwl 
[Detaching after fork from child process 5287]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ebe4b3 in wlr_backend_get_renderer (backend=0x0) at ../backend/backend.c:54
54		if (backend->impl->get_renderer) {
#0  0x00007ffff7ebe4b3 in wlr_backend_get_renderer (backend=0x0) at ../backend/backend.c:54
#1  0x000055555555c36b in setup () at dwl.c:1478
#2  0x000055555555cfb7 in main (argc=1, argv=0x7fffffffeca8) at dwl.c:1942

Do you plan to do any CI with testing/fuzzing for this nice little program?

**Comment by matu3ba** [comment]
Installing `mesa-dri-intel`, `qemu-hw-display-qxl`,`xf86-video-qxl` fixed the segfault.
